module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  important: true,
  theme: {
    darkMode: false,
    colors: {
      transparent: "transparent",
      Elephant: "#B8B8B8",
      Black: "#000",
      Vulcan: "#303036",
      Asphalt: "#48484E",
      Charcoal: "#64646E",
      Gunmetal: "#8D8D96",
      Misty: "#B4B4BE",
      Pewter: "#D6D6DE",
      Snuff: "#E8E8EF",
      Smoke: "#F4F4F8",
      white: "#FFF",
      Electric: "#8844BB",
      Purple: "#9933FF",
      Royal: "#446BFF",
      Anakiwa: "#BECEFF",
      Snuff: "#E8E8EF",
      Ruby: "#F03E58",
      Bubblegum: "#F88096",
      Purple: "#44A663",
      Tea: "#EDFEED",
      Dandelion: "#FFD65C",
      Amber: "#FFB044",
      Black: "#242428",
      Bubblegum: "#F47587",
      Scarlet: "#FD4E3B",
      Danger: "#FD4E3B",
      Anakiwa: "#BECEFF",
      Tea: "#E8F6ED",
      Skin: "#FEE",
      Cerulean: "#00B5CA",
      California: "#FA9E14",
      Melon: "#FFB8C2",
    },
    extend: {
      fontFamily: {
        IRANSansXFaNum: ["var(--font-iran-sans)"],
        Koodak: ["var(--font-koodak)"],
      },
      boxShadow: {
        "3xl": "0px 8px 32px rgba(100, 102, 111, 0.24)",
        "2xl": "0px 4px 16px 0px rgba(36, 36, 40, 0.12)",
      },
    },
  },
};
